# Generated by Django 4.0.6 on 2022-11-21 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_rename_product_products'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
