# Generated by Django 4.0.6 on 2023-01-07 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
